In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

## pandas数据结构介绍

### Series

In [3]:
#Series 类似于一维数组
#索引（左） 值（右）
obj = pd.Series([4,7,-5,3])

In [4]:
#未指定索引，则会自动创建一个0-N-1（N为数据长度）的整数型索引
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3],index=['d','b','a','c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d']

4

In [13]:
obj2[obj2 >0]

d    4
b    7
c    3
dtype: int64

In [14]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [16]:
obj3 =pd.Series(sdata)

In [18]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states = ['California','Ohio','Oregon','Texas']

In [20]:
obj4 = pd.Series(sdata,index=states)

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

### DataFrame

In [26]:
data = {'state':['Ohio','Ohio','Ohio','Neveda','Neveda','Nevedia'], 'year':[2000,2001,2002,2001,2002,2003], 'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [27]:
frame = pd.DataFrame(data)

In [28]:
frame

state  year  pop
0     Ohio  2000  1.5
1     Ohio  2001  1.7
2     Ohio  2002  3.6
3   Neveda  2001  2.4
4   Neveda  2002  2.9
5  Nevedia  2003  3.2

In [29]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Neveda  2001  2.4
4  Neveda  2002  2.9

In [5]:
from pandas import DataFrame
data = {'state':['Ohio','Ohio','Ohio','Neveda','Neveda','Nevedia'], 'year':[2000,2001,2002,2001,2002,2003], 'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=DataFrame(data,columns =['year','state','pop'])

In [6]:
frame

year    state  pop
0  2000     Ohio  1.5
1  2001     Ohio  1.7
2  2002     Ohio  3.6
3  2001   Neveda  2.4
4  2002   Neveda  2.9
5  2003  Nevedia  3.2

In [7]:
frame['state']

0       Ohio
1       Ohio
2       Ohio
3     Neveda
4     Neveda
5    Nevedia
Name: state, dtype: object

In [12]:
frame.loc[1]

year     2001
state    Ohio
pop       1.7
Name: 1, dtype: object

In [14]:
frame['debt'] = 16.5

In [15]:
frame

year    state  pop  debt
0  2000     Ohio  1.5  16.5
1  2001     Ohio  1.7  16.5
2  2002     Ohio  3.6  16.5
3  2001   Neveda  2.4  16.5
4  2002   Neveda  2.9  16.5
5  2003  Nevedia  3.2  16.5

In [17]:
import numpy as np

In [20]:
frame

year    state  pop  debt
0  2000     Ohio  1.5  16.5
1  2001     Ohio  1.7  16.5
2  2002     Ohio  3.6  16.5
3  2001   Neveda  2.4  16.5
4  2002   Neveda  2.9  16.5
5  2003  Nevedia  3.2  16.5

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
frame['debt'] = np.arange(6.)

In [23]:
frame

year    state  pop  debt
0  2000     Ohio  1.5   0.0
1  2001     Ohio  1.7   1.0
2  2002     Ohio  3.6   2.0
3  2001   Neveda  2.4   3.0
4  2002   Neveda  2.9   4.0
5  2003  Nevedia  3.2   5.0

In [24]:
frame.values

array([[2000, 'Ohio', 1.5, 0.0],
       [2001, 'Ohio', 1.7, 1.0],
       [2002, 'Ohio', 3.6, 2.0],
       [2001, 'Neveda', 2.4, 3.0],
       [2002, 'Neveda', 2.9, 4.0],
       [2003, 'Nevedia', 3.2, 5.0]], dtype=object)