## ndarray :多维数组对象

In [1]:
import numpy as np

In [5]:
data = np.random.randn(2,3)
data

array([[ 0.17984151, -0.6177783 , -1.63378474],
       [ 0.51630531, -0.33481836,  0.18494922]])

In [6]:
data * 10

array([[  1.79841511,  -6.17778297, -16.33784737],
       [  5.16305308,  -3.34818356,   1.84949225]])

In [7]:
data +data

array([[ 0.35968302, -1.23555659, -3.26756947],
       [ 1.03261062, -0.66963671,  0.36989845]])

In [8]:
data.dtype

dtype('float64')

In [10]:
data.shape

(2, 3)

### 创建ndarray

In [11]:
data1 = [6,7.5,8,0,1]

In [12]:
arr1 =np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')