# 数据操作

In [5]:
#使用arange 函数创建一个行向量
from mxnet import nd
x =nd.arange(12)
# 生成一个长度为12的一维数组，
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [6]:
x.shape

(12,)

In [7]:
x.size

12

In [9]:
# 将行向量形状改为（3，4） ，即为3行4列的矩阵
x= x.reshape(3,4)
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [10]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [11]:
#随机生成NDArray中每个元素的值，
#创建一个形状（3，4）的NDArray , 它的每个元素采样于均值为0。标准差为1的正态分布
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [12]:
y = nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

## 运算

In [13]:
#按元素加法
x +y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [14]:
#按元素乘法
x *y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [15]:
#按元素除法
x/y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [16]:
#按元素指数运算
y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [17]:
#使用dot函数， 做矩阵运算
# x  与 y的转置做矩阵乘法
nd.dot(x,y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [18]:
#NDArray合并
#行上（维度为0，即形状中最嘴边的元素）连结（concatenate）两个矩阵
nd.concat(x,y,dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [19]:
#在列上（维度为1，即形状中左起第二个元素）连结（concatenate）两个矩阵
nd.concat(x,y,dim=1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [20]:
# x,y在相同位置的条件判断为真（值相等），新的NDArray ,在相同位置为1，反之为0
x==y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [21]:
#所有元素求和得到只有一个元素的NDArray
x.sum()


[66.]
<NDArray 1 @cpu(0)>

In [22]:
x.norm().asscalar()

22.494442

## 广播机制

In [23]:
a = nd.arange(3).reshape((3,1))
b=nd.arange(2).reshape((1,2))
a,b

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [24]:
a+b


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

## 索引

#索引(index)代表了元素的位置，NDArray的索引从0开始，逐一递增

In [27]:
x[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [28]:
x[1:2]


[[4. 5. 6. 7.]]
<NDArray 1x4 @cpu(0)>

In [29]:
x[1,2]


[6.]
<NDArray 1 @cpu(0)>

In [30]:
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>